// Builds the U6 "folded underline" lockup as font-independent SVG (text converted to outlines).
// Geometry mirrors the CSS in previews/brand-u6.html. Run: cd tools && node gen-lockups.js
const fs = require('fs');
const path = require('path');
const opentype = require('opentype.js');
const sharp = require('sharp');

const ROOT = path.join(__dirname, '..');
const LOGO = path.join(ROOT, 'logo');
const OUT = path.join(LOGO, 'lockup');
fs.mkdirSync(OUT, { recursive: true });

// Same Inter 700 file Google Fonts serves to browsers (v20), so outlines and metrics match the web lockup.
const font = opentype.parse(fs.readFileSync(path.join(__dirname, 'fonts', 'Inter-700-googlefonts-v20.ttf')).buffer);
// Pair kerning the browser applies via a GPOS lookup that opentype.js does not read (font units).
// Measured from Chrome's rendering of the reference lockup in previews/brand-u6.html.
const GPOS_KERN = { re: -50 };
const upm = font.unitsPerEm;
const ASC = font.tables.hhea.ascender / upm;
const DESC = -font.tables.hhea.descender / upm;

const N = 100;                 // name size; everything else is proportional
const D = 0.7 * N;             // domain size
const TRACK = -0.02 * N;       // letter-spacing set on the wordmark, inherited as an absolute length
const T = 0.14 * D;            // underline thickness and gap
const CUT = 0.081 * D;         // 30° end cut (thickness × tan30)

// Line-height:1 box for a run of text: where its top/bottom sit relative to the baseline.
const boxTop = (base, size) => base - ASC * size - (1 - (ASC + DESC)) * size / 2;

// Lay out glyphs left to right with kerning + tracking; returns path data and the advance.
function run(text, x, base, size, f = font, track = TRACK) {
  const scale = size / upm;
  let d = '';
  const glyphs = [...text].map(ch => f.charToGlyph(ch)); // plain cmap lookup; no ligatures needed for these strings
  glyphs.forEach((g, i) => {
    d += g.getPath(x, base, size).toPathData(2);
    x += g.advanceWidth * scale + track;
    if (i < glyphs.length - 1) x += (f.getKerningValue(g, glyphs[i + 1]) + (GPOS_KERN[text[i] + text[i + 1]] || 0)) * scale;
  });
  return { d, end: x };
}

// The wordmark with its baseline at y = base and left edge at x0.
function wordmark(x0, base, c) {
  const name = run('resale', x0, base, N);
  const dot = run('.', name.end, base, D);
  const com = run('com.pk', dot.end, base, D);
  const uL = dot.end, uR = com.end;
  const uBottom = boxTop(base, D) + D;
  const barTop = uBottom + T, barBot = uBottom + 2 * T;
  const fW = 0.308 * D, fH = 0.364 * D, fx = uR + 0.02 * D - fW, fTop = barTop;
  const f = n => n.toFixed(2);
  const svg =
    `<path fill="${c.name}" d="${name.d}"/>\n` +
    `<path fill="${c.dom}" d="${dot.d}${com.d}"/>\n` +
    `<polygon fill="${c.line}" points="${f(uL + CUT)},${f(barTop)} ${f(uR)},${f(barTop)} ${f(uR - CUT)},${f(barBot)} ${f(uL)},${f(barBot)}"/>\n` +
    `<polygon fill="${c.fold}" points="${f(fx)},${f(fTop)} ${f(fx + fW)},${f(fTop)} ${f(fx + fW)},${f(fTop + fH * 0.62)} ${f(fx)},${f(fTop + fH)}"/>`;
  return { svg, right: Math.max(uR, fx + fW), textRight: uR, bottom: fTop + fH, top: boxTop(base, N) };
}

// Symbol artwork, re-used from the existing logo files.
const inner = file => fs.readFileSync(path.join(LOGO, file), 'utf8')
  .replace(/^[\s\S]*?<\/title>\s*(<!--[\s\S]*?-->)?/, '').replace(/<\/svg>\s*$/, '');
const symbol = (file, x, y, size) =>
  `<svg x="${x.toFixed(2)}" y="${y.toFixed(2)}" width="${size}" height="${size}" viewBox="1008 930 3000 3000">${inner(file)}</svg>`;

const C = {
  light: { name: '#024E53', dom: '#64748B', line: '#FD7009', fold: '#E55106', mark: 'resale-logo-master.svg' },
  small: { name: '#024E53', dom: '#64748B', line: '#FD7009', fold: '#E55106', mark: 'resale-logo-flat.svg' },
  dark: { name: '#FFFFFF', dom: '#94A3B8', line: '#FD7009', fold: '#E55106', mark: 'resale-logo-mono-white.svg' },
  teal: { name: '#FFFFFF', dom: '#CCDCDD', line: '#FD7009', fold: '#E55106', mark: 'resale-logo-mono-white.svg' },
  ink: { name: '#0F172A', dom: '#0F172A', line: '#0F172A', fold: '#0F172A', mark: 'resale-logo-mono-ink.svg' },
  white: { name: '#FFFFFF', dom: '#FFFFFF', line: '#FFFFFF', fold: '#FFFFFF', mark: 'resale-logo-mono-white.svg' },
};

const doc = (body, x, y, w, h, title) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)}" width="${Math.round(w * 2)}" height="${Math.round(h * 2)}" role="img" aria-labelledby="title">\n` +
  `<title id="title">${title}</title>\n<!-- resale.com.pk U6 lockup v1.1. Text is outlined Inter 700. Generated by tools/gen-lockups.js; do not edit by hand. -->\n${body}\n</svg>\n`;

const PAD = 0.12 * N; // tight trim margin; clear space is specified in the guidelines, not baked in

function horizontal(c) {
  const S = 1.55 * N, gap = 0.42 * N, base = 0;
  const top = boxTop(base, N), centre = top + N / 2;
  const wm = wordmark(S + gap, base, c);
  const y0 = Math.min(centre - S / 2, top) - PAD, y1 = Math.max(centre + S / 2, wm.bottom) + PAD;
  return doc(symbol(c.mark, 0, centre - S / 2, S) + '\n' + wm.svg, -PAD, y0, wm.right + 2 * PAD, y1 - y0, 'resale.com.pk');
}

function stacked(c) {
  const S = 2.6 * N, gap = 0.5 * N;
  const probe = wordmark(0, 0, c); // measure width first
  const wmW = probe.textRight, width = Math.max(S, probe.right); // centre on the text box, as CSS does
  const wmTop = S + gap, base = wmTop - boxTop(0, N);
  const wm = wordmark((width - wmW) / 2, base, c);
  return doc(symbol(c.mark, (width - S) / 2, 0, S) + '\n' + wm.svg, -PAD, -PAD, width + 2 * PAD, wm.bottom + 2 * PAD, 'resale.com.pk');
}

function wordOnly(c) {
  const wm = wordmark(0, 0, c);
  return doc(wm.svg, -PAD, wm.top - PAD, wm.right + 2 * PAD, wm.bottom - wm.top + 2 * PAD, 'resale.com.pk');
}

// ---------- Header lockup (optical small size) ----------
// For lockups rendered 28–44px tall (name ≈ 18–28px). The master proportions are drawn for large
// sizes; shrunk to a header they look cramped and the 2px stroke falls between pixel rows. This
// version opens the letter-spacing, sets ".com.pk" in SemiBold slightly larger, and builds the file
// at an exact pixel height with the baseline, stroke and fold snapped to whole pixels.
const font600 = opentype.parse(fs.readFileSync(path.join(__dirname, 'fonts', 'Inter-600-googlefonts-v20.ttf')).buffer);
const HEADER = { track: -0.005, domRatio: 0.72, domTrack: 0.012, gap: 0.45 };

function headerLockup(H, c, gap = HEADER.gap, track = HEADER.track) {
  const S = H;                         // symbol fills the file height
  const n = S / 1.55, d = HEADER.domRatio * n;
  const centre = S / 2;
  const base = Math.round(centre + 0.36 * n); // baseline 0.36 N below the symbol centre, on a whole pixel
  const x0 = Math.round(S + gap * n);
  const name = run('resale', x0, base, n, font, track * n);
  const dot = run('.', name.end, base, d, font600, HEADER.domTrack * d);
  const com = run('com.pk', dot.end, base, d, font600, HEADER.domTrack * d);
  const uL = Math.round(dot.end), uR = Math.round(com.end - HEADER.domTrack * d); // drop trailing tracking
  const t = Math.max(2, Math.round(0.1 * n));              // stroke: whole pixels, never under 2
  const barTop = base + Math.max(3, Math.round(0.19 * n));
  const barBot = barTop + t;
  const cut = Math.max(1, Math.round(t * Math.tan(Math.PI / 6)));
  const fW = Math.max(3, Math.round(0.22 * n)), fH = Math.max(t + 2, Math.round(0.26 * n));
  const fx = uR - fW + Math.max(0, Math.round(0.02 * d));
  const fold = `${fx},${barTop} ${fx + fW},${barTop} ${fx + fW},${barTop + Math.round(fH * 0.62)} ${fx},${barTop + fH}`;
  const W = Math.ceil(Math.max(fx + fW, uR));
  const body =
    symbol(c.mark, 0, 0, S) + '\n' +
    `<path fill="${c.name}" d="${name.d}"/>\n` +
    `<path fill="${c.dom}" d="${dot.d}${com.d}"/>\n` +
    `<polygon fill="${c.line}" points="${uL + cut},${barTop} ${uR},${barTop} ${uR - cut},${barBot} ${uL},${barBot}"/>\n` +
    `<polygon fill="${c.fold}" points="${fold}"/>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${S}" width="${W}" height="${S}" role="img" aria-labelledby="title">\n` +
    `<title id="title">resale.com.pk</title>\n<!-- resale.com.pk U6 header lockup, pixel-fitted for ${S}px height. Use at exactly ${W}×${S} CSS px. Generated by tools/gen-lockups.js. -->\n${body}\n</svg>\n`;
}

// Width caps requested by the web team (header must fit beside three 44px buttons on phones).
// When a cap applies, close the symbol gap first (down to 0.36 N), then the name tracking (down to -1.2%).
const HEADER_MAX_W = { 28: 140, 36: 180 };
function fitHeader(H, c) {
  const max = HEADER_MAX_W[H];
  if (!max) return headerLockup(H, c);
  for (let track = HEADER.track; track >= -0.012 - 1e-9; track -= 0.001)
    for (let gap = HEADER.gap; gap >= 0.36 - 1e-9; gap -= 0.01) {
      const svg = headerLockup(H, c, gap, track);
      if (+svg.match(/width="(\d+)"/)[1] <= max) return svg;
    }
  throw new Error('header-' + H + ' cannot fit ' + max + 'px');
}

const HEADER_SIZES = [28, 32, 36, 40, 42, 44, 48];
const headerFiles = {};
for (const H of HEADER_SIZES) {
  headerFiles[`resale-lockup-header-${H}.svg`] = fitHeader(H, C.light); // detailed symbol at every size (owner decision)
  headerFiles[`resale-lockup-header-${H}-dark.svg`] = fitHeader(H, C.dark);
}

const files = {
  ...headerFiles,
  'resale-lockup.svg': horizontal(C.light),
  'resale-lockup-small.svg': horizontal(C.small),
  'resale-lockup-dark.svg': horizontal(C.dark),
  'resale-lockup-on-teal.svg': horizontal(C.teal),
  'resale-lockup-ink.svg': horizontal(C.ink),
  'resale-lockup-white.svg': horizontal(C.white),
  'resale-lockup-stacked.svg': stacked(C.light),
  'resale-lockup-stacked-dark.svg': stacked(C.dark),
  'resale-lockup-stacked-ink.svg': stacked(C.ink),
  'resale-lockup-stacked-white.svg': stacked(C.white),
  'resale-wordmark.svg': wordOnly(C.light),
  'resale-wordmark-dark.svg': wordOnly(C.dark),
  'resale-wordmark-ink.svg': wordOnly(C.ink),
  'resale-wordmark-white.svg': wordOnly(C.white),
};

(async () => {
  for (const [name, svg] of Object.entries(files)) {
    fs.writeFileSync(path.join(OUT, name), svg);
    if (name.includes('-header-')) {
      // Pixel-fitted: export exact 1x/2x/3x PNGs (retina phones) instead of a resized 1200px image
      const [, w, h] = svg.match(/width="(\d+)" height="(\d+)"/).map(Number);
      for (const k of [1, 2, 3]) {
        const out = name.replace('.svg', k === 1 ? '.png' : `@${k}x.png`);
        await sharp(Buffer.from(svg), { density: 72 * k * 2 }).resize(w * k, h * k).png().toFile(path.join(OUT, out));
      }
      continue;
    }
    // 1200px-wide transparent PNG for tools that can't take SVG
    await sharp(Buffer.from(svg), { density: 300 }).resize({ width: 1200 }).png().toFile(path.join(OUT, name.replace('.svg', '-1200.png')));
  }
  console.log(Object.keys(files).length, 'lockups written to logo/lockup/');
})();
